segmentsVertB = segments(songorders(1,:),b_dx_normvert);
segmentsVertC = segments(songorders(2,:),c_dx_normvert);
segmentsVertD = segments(songorders(3,:),d_dx_normvert);
segmentsVertE = segments(songorders(4,:),e_dx_normvert);
segmentsVertF = segments(songorders(5,:),f_dx_normvert);
segmentsVertG = segments(songorders(6,:),g_dx_normvert);
segmentsVertH = segments(songorders(7,:),h_dx_normvert);
segmentsVertI = segments(songorders(8,:),i_dx_normvert);
segmentsVertJ = segments(songorders(9,:),j_dx_normvert);
segmentsVertK = segments(songorders(10,:),k_dx_normvert);
segmentsVertL = segments(songorders(11,:),l_dx_normvert);
segmentsVertM = segments(songorders(12,:),m_dx_normvert);

segmentedavgVertB = [mean(segmentsVertB(1).data(:,3:end),'omitnan')' mean(segmentsVertB(2).data(:,3:end),'omitnan')' mean(segmentsVertB(3).data(:,3:end),'omitnan')' mean(segmentsVertB(4).data(:,3:end),'omitnan')' mean(segmentsVertB(5).data(:,3:end),'omitnan')' mean(segmentsVertB(6).data(:,3:end),'omitnan')' mean(segmentsVertB(7).data(:,3:end),'omitnan')' mean(segmentsVertB(8).data(:,3:end),'omitnan')' mean(segmentsVertB(9).data(:,3:end),'omitnan')' mean(segmentsVertB(10).data(:,3:end),'omitnan')' mean(segmentsVertB(11).data(:,3:end),'omitnan')' mean(segmentsVertB(12).data(:,3:end),'omitnan')' mean(segmentsVertB(13).data(:,3:end),'omitnan')'];
segmentedavgVertC = [mean(segmentsVertC(1).data(:,3:end),'omitnan')' mean(segmentsVertC(2).data(:,3:end),'omitnan')' mean(segmentsVertC(3).data(:,3:end),'omitnan')' mean(segmentsVertC(4).data(:,3:end),'omitnan')' mean(segmentsVertC(5).data(:,3:end),'omitnan')' mean(segmentsVertC(6).data(:,3:end),'omitnan')' mean(segmentsVertC(7).data(:,3:end),'omitnan')' mean(segmentsVertC(8).data(:,3:end),'omitnan')' mean(segmentsVertC(9).data(:,3:end),'omitnan')' mean(segmentsVertC(10).data(:,3:end),'omitnan')' mean(segmentsVertC(11).data(:,3:end),'omitnan')' mean(segmentsVertC(12).data(:,3:end),'omitnan')' mean(segmentsVertC(13).data(:,3:end),'omitnan')'];
segmentedavgVertD = [mean(segmentsVertD(1).data(:,3:end),'omitnan')' mean(segmentsVertD(2).data(:,3:end),'omitnan')' mean(segmentsVertD(3).data(:,3:end),'omitnan')' mean(segmentsVertD(4).data(:,3:end),'omitnan')' mean(segmentsVertD(5).data(:,3:end),'omitnan')' mean(segmentsVertD(6).data(:,3:end),'omitnan')' mean(segmentsVertD(7).data(:,3:end),'omitnan')' mean(segmentsVertD(8).data(:,3:end),'omitnan')' mean(segmentsVertD(9).data(:,3:end),'omitnan')' mean(segmentsVertD(10).data(:,3:end),'omitnan')' mean(segmentsVertD(11).data(:,3:end),'omitnan')' mean(segmentsVertD(12).data(:,3:end),'omitnan')' mean(segmentsVertD(13).data(:,3:end),'omitnan')'];
segmentedavgVertE = [mean(segmentsVertE(1).data(:,3:end),'omitnan')' mean(segmentsVertE(2).data(:,3:end),'omitnan')' mean(segmentsVertE(3).data(:,3:end),'omitnan')' mean(segmentsVertE(4).data(:,3:end),'omitnan')' mean(segmentsVertE(5).data(:,3:end),'omitnan')' mean(segmentsVertE(6).data(:,3:end),'omitnan')' mean(segmentsVertE(7).data(:,3:end),'omitnan')' mean(segmentsVertE(8).data(:,3:end),'omitnan')' mean(segmentsVertE(9).data(:,3:end),'omitnan')' mean(segmentsVertE(10).data(:,3:end),'omitnan')' mean(segmentsVertE(11).data(:,3:end),'omitnan')' mean(segmentsVertE(12).data(:,3:end),'omitnan')' mean(segmentsVertE(13).data(:,3:end),'omitnan')'];
segmentedavgVertF = [mean(segmentsVertF(1).data(:,3:end),'omitnan')' mean(segmentsVertF(2).data(:,3:end),'omitnan')' mean(segmentsVertF(3).data(:,3:end),'omitnan')' mean(segmentsVertF(4).data(:,3:end),'omitnan')' mean(segmentsVertF(5).data(:,3:end),'omitnan')' mean(segmentsVertF(6).data(:,3:end),'omitnan')' mean(segmentsVertF(7).data(:,3:end),'omitnan')' mean(segmentsVertF(8).data(:,3:end),'omitnan')' mean(segmentsVertF(9).data(:,3:end),'omitnan')' mean(segmentsVertF(10).data(:,3:end),'omitnan')' mean(segmentsVertF(11).data(:,3:end),'omitnan')' mean(segmentsVertF(12).data(:,3:end),'omitnan')' mean(segmentsVertF(13).data(:,3:end),'omitnan')'];
segmentedavgVertG = [mean(segmentsVertG(1).data(:,3:end),'omitnan')' mean(segmentsVertG(2).data(:,3:end),'omitnan')' mean(segmentsVertG(3).data(:,3:end),'omitnan')' mean(segmentsVertG(4).data(:,3:end),'omitnan')' mean(segmentsVertG(5).data(:,3:end),'omitnan')' mean(segmentsVertG(6).data(:,3:end),'omitnan')' mean(segmentsVertG(7).data(:,3:end),'omitnan')' mean(segmentsVertG(8).data(:,3:end),'omitnan')' mean(segmentsVertG(9).data(:,3:end),'omitnan')' mean(segmentsVertG(10).data(:,3:end),'omitnan')' mean(segmentsVertG(11).data(:,3:end),'omitnan')' mean(segmentsVertG(12).data(:,3:end),'omitnan')' mean(segmentsVertG(13).data(:,3:end),'omitnan')'];
segmentedavgVertH = [mean(segmentsVertH(1).data(:,3:end),'omitnan')' mean(segmentsVertH(2).data(:,3:end),'omitnan')' mean(segmentsVertH(3).data(:,3:end),'omitnan')' mean(segmentsVertH(4).data(:,3:end),'omitnan')' mean(segmentsVertH(5).data(:,3:end),'omitnan')' mean(segmentsVertH(6).data(:,3:end),'omitnan')' mean(segmentsVertH(7).data(:,3:end),'omitnan')' mean(segmentsVertH(8).data(:,3:end),'omitnan')' mean(segmentsVertH(9).data(:,3:end),'omitnan')' mean(segmentsVertH(10).data(:,3:end),'omitnan')' mean(segmentsVertH(11).data(:,3:end),'omitnan')' mean(segmentsVertH(12).data(:,3:end),'omitnan')' mean(segmentsVertH(13).data(:,3:end),'omitnan')'];
segmentedavgVertI = [mean(segmentsVertI(1).data(:,3:end),'omitnan')' mean(segmentsVertI(2).data(:,3:end),'omitnan')' mean(segmentsVertI(3).data(:,3:end),'omitnan')' mean(segmentsVertI(4).data(:,3:end),'omitnan')' mean(segmentsVertI(5).data(:,3:end),'omitnan')' mean(segmentsVertI(6).data(:,3:end),'omitnan')' mean(segmentsVertI(7).data(:,3:end),'omitnan')' mean(segmentsVertI(8).data(:,3:end),'omitnan')' mean(segmentsVertI(9).data(:,3:end),'omitnan')' mean(segmentsVertI(10).data(:,3:end),'omitnan')' mean(segmentsVertI(11).data(:,3:end),'omitnan')' mean(segmentsVertI(12).data(:,3:end),'omitnan')' mean(segmentsVertI(13).data(:,3:end),'omitnan')'];
segmentedavgVertJ = [mean(segmentsVertJ(1).data(:,3:end),'omitnan')' mean(segmentsVertJ(2).data(:,3:end),'omitnan')' mean(segmentsVertJ(3).data(:,3:end),'omitnan')' mean(segmentsVertJ(4).data(:,3:end),'omitnan')' mean(segmentsVertJ(5).data(:,3:end),'omitnan')' mean(segmentsVertJ(6).data(:,3:end),'omitnan')' mean(segmentsVertJ(7).data(:,3:end),'omitnan')' mean(segmentsVertJ(8).data(:,3:end),'omitnan')' mean(segmentsVertJ(9).data(:,3:end),'omitnan')' mean(segmentsVertJ(10).data(:,3:end),'omitnan')' mean(segmentsVertJ(11).data(:,3:end),'omitnan')' mean(segmentsVertJ(12).data(:,3:end),'omitnan')' mean(segmentsVertJ(13).data(:,3:end),'omitnan')'];
segmentedavgVertK = [mean(segmentsVertK(1).data(:,3:end),'omitnan')' mean(segmentsVertK(2).data(:,3:end),'omitnan')' mean(segmentsVertK(3).data(:,3:end),'omitnan')' mean(segmentsVertK(4).data(:,3:end),'omitnan')' mean(segmentsVertK(5).data(:,3:end),'omitnan')' mean(segmentsVertK(6).data(:,3:end),'omitnan')' mean(segmentsVertK(7).data(:,3:end),'omitnan')' mean(segmentsVertK(8).data(:,3:end),'omitnan')' mean(segmentsVertK(9).data(:,3:end),'omitnan')' mean(segmentsVertK(10).data(:,3:end),'omitnan')' mean(segmentsVertK(11).data(:,3:end),'omitnan')' mean(segmentsVertK(12).data(:,3:end),'omitnan')' mean(segmentsVertK(13).data(:,3:end),'omitnan')'];
segmentedavgVertL = [mean(segmentsVertL(1).data(:,3:end),'omitnan')' mean(segmentsVertL(2).data(:,3:end),'omitnan')' mean(segmentsVertL(3).data(:,3:end),'omitnan')' mean(segmentsVertL(4).data(:,3:end),'omitnan')' mean(segmentsVertL(5).data(:,3:end),'omitnan')' mean(segmentsVertL(6).data(:,3:end),'omitnan')' mean(segmentsVertL(7).data(:,3:end),'omitnan')' mean(segmentsVertL(8).data(:,3:end),'omitnan')' mean(segmentsVertL(9).data(:,3:end),'omitnan')' mean(segmentsVertL(10).data(:,3:end),'omitnan')' mean(segmentsVertL(11).data(:,3:end),'omitnan')' mean(segmentsVertL(12).data(:,3:end),'omitnan')' mean(segmentsVertL(13).data(:,3:end),'omitnan')'];
segmentedavgVertM = [mean(segmentsVertM(1).data(:,3:end),'omitnan')' mean(segmentsVertM(2).data(:,3:end),'omitnan')' mean(segmentsVertM(3).data(:,3:end),'omitnan')' mean(segmentsVertM(4).data(:,3:end),'omitnan')' mean(segmentsVertM(5).data(:,3:end),'omitnan')' mean(segmentsVertM(6).data(:,3:end),'omitnan')' mean(segmentsVertM(7).data(:,3:end),'omitnan')' mean(segmentsVertM(8).data(:,3:end),'omitnan')' mean(segmentsVertM(9).data(:,3:end),'omitnan')' mean(segmentsVertM(10).data(:,3:end),'omitnan')' mean(segmentsVertM(11).data(:,3:end),'omitnan')' mean(segmentsVertM(12).data(:,3:end),'omitnan')' mean(segmentsVertM(13).data(:,3:end),'omitnan')'];

